### PR TITLE
Refactor dialogs

### PR DESCRIPTION
**Pull request by rotsee**
Refactored the dialog components for readability and easier maintenance, and ironed out a few bugs and quirks in the process. 

 - tree adding logic moved to addTreeDialog
 - tree viewing logic moved to viewTreeDialog
 - Use Vue bindings for cleaner code
 - The Map component is now mostly a map component :)

Closes https://github.com/fruktkartan/fruktkartan/issues/35

### CODE REVIEW

**Comment by rotsee** [comment]
> I'm run this locally, didn't see any breakage. _But_ I can't test the actual image issue, as I can't (easily at least) run the s3 stuff locally...

I've tested it production :)

**Comment by rotsee** [comment]
@quite I'm stuck in git merge conflict hell here. Would you mind putting this in production?

**Comment by quite** [comment]
@rotsee somehow something funky entered production branch... I'm trying to always do only fast-forward merges from master to production. Have to allow force-pushes temporarily to resolve it. Done!

**Comment by rotsee** [comment]
@quite Thank you! I probably did something funny when merging. I promise to be careful in the future!

**Pull request merged**
